# Generated by Django 5.2.17 on 2026-09-29 12:56

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(max_length=50)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stored_image', to='auctions.auction')),
            ],
        ),
    ]
