# Generated by Django 3.0.8 on 2020-10-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200930_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='auctions.Auction'),
        ),
    ]
