# Generated by Django 3.0.8 on 2020-10-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201006_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auction_item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction_item',
            field=models.ManyToManyField(blank=True, to='auctions.Auction'),
        ),
    ]
