# Generated by Django 3.0.8 on 2020-10-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201006_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auction_item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_item', to='auctions.Auction'),
        ),
    ]
