# Generated by Django 3.0.8 on 2020-10-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201006_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_item', to='auctions.Auction'),
        ),
    ]
