# Generated by Django 3.0.8 on 2020-10-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201006_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
