# Generated by Django 3.0.8 on 2020-10-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_notificationmsg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
