# Generated by Django 3.0.8 on 2020-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmsg',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
