# Generated by Django 3.0.8 on 2020-11-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_notificationmsg_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmsg',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-31'),
            preserve_default=False,
        ),
    ]
