# Generated by Django 3.0.8 on 2020-11-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_notificationmsg_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='modify_date',
            field=models.DateTimeField(default='2020-11-01'),
            preserve_default=False,
        ),
    ]
